### ISSUE TITLE
'top' positions show at the bottom

### ISSUE THREAD

**Issue by dandv** [voidale/bootstrap-alerts#1]
Just tried this at http://bootstrap-alerts-voidale.meteor.com/

```
Alerts.Options.position = 'bottom-left'; Alerts.success('bottom-left');
Alerts.Options.position = 'top-right'; Alerts.success('top-right');
```

![image](https://cloud.githubusercontent.com/assets/33569/7229244/55d3341e-e716-11e4-9947-f1727d8470e3.png)

PS: :+1: for some buttons in the demo could to trigger alerts.

**Comment by markudevelop** [comment]
@dandv yep you're right it's an issue I will fix this later today and update the demo(had no time) but It's still work in progress, Didn't expect anyone to find this. But I'm already using the package so it should be good to use after this fix :)
